import 'bootstrap-icons/font/bootstrap-icons.css';

import 'bootstrap/dist/css/bootstrap.css';

import 'glightbox/dist/css/glightbox.css';

import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "./globals.css";
import Header from './components/Header';
import ScrollBtn from './components/ScrollBtn';
import Footer from './sections/Footer';


const lora = Lora({ subsets: ['latin'], weight: ['400', '500', '600', '700'], variable: '--font-lora' });

export const metadata: Metadata = {
  title: "Grace's Restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lora.className}>
        <Header />
        {children}
        <Footer />
        <ScrollBtn />
      </body>
      {/*<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" 
      crossOrigin="anonymous"></script>*/}
    </html>
  );
}
